blank_issues_enabled: false
contact_links:
  - name: "Feature request"
    about: "Check our Public Roadmap to request new features on Docker Desktop."
    url: "https://github.com/docker/roadmap/issues"
  - name: "Docker support"
    about: "Get the help you need to build, share, and run your Docker applications."
    url: "https://www.docker.com/support/"
