name: Build and Deploy DocFX to GitHub Pages

on:
  push:
    branches:
      - main # Chạy khi có sự thay đổi trên nhánh main

jobs:
  build:
    runs-on: ubuntu-latest # Chạy trên môi trường Ubuntu

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up .NET (DocFX yêu cầu .NET Core)
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      # Cài đặt DocFX
      - name: Install DocFX
        run: |
          dotnet tool install -g docfx

      # Tạo tài liệu với DocFX
      - name: Build DocFX site
        run: |
          docfx build docfx.json

      # Triển khai tài liệu lên GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # Nhánh để triển khai (thường là gh-pages)
          folder: _site # Thư mục output từ DocFX
          token: ${{ secrets.GITHUB_TOKEN }} # Cung cấp token cho phép deploy
